# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-22 16:47
from __future__ import unicode_literals
import sys
from django.db import migrations, models
from django.core.management import call_command

def load_test_fixtures(apps, schema_editor):
    if sys.argv[1:2] == ['test']:
        print("fuck the tests")
        call_command('loaddata', '../master_data/db.sqlite3', verbosity=2)

class Migration(migrations.Migration):

    dependencies = [
        ('cognation', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='locus',
            index=models.Index(fields=['locus', 'sat'], name='cognation_l_locus_e2fc2e_idx'),
        ),
        migrations.RunPython(load_test_fixtures)
    ]
